Repository Patribots4738/ChargedUp2023, pull requests merged in 2023-03, with the labels that each got.

#56 LEDs to main
  src/main/java/calc/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/hardware/ArduinoController.java
  src/main/java/hardware/Swerve.java
Labels: enhancement

#90 Comment the changes in swerve.drive #72
  .pathplanner/settings.json
  src/main/java/hardware/Swerve.java
Labels: documentation

#86 Commented the Names for all indexes in the ARM_POSITIONS array #81
  src/main/java/calc/Constants.java
Labels: documentation

#96 Auto align to the nearest index of the grid that the robot is at... #95
  src/main/java/auto/AutoAlignment.java
  src/main/java/auto/SwerveTrajectory.java
  src/main/java/calc/Constants.java
  src/main/java/calc/PhotonCameraPose.java
  src/main/java/frc/robot/Robot.java
  src/main/java/hardware/Swerve.java
Labels: enhancement, logic, needs testing, teleop

#106 Add rotational alignment to the new auto alignment branch
  src/main/java/auto/AutoAlignment.java
  src/main/java/frc/robot/Robot.java
Labels: enhancement, teleop

#105 Revamp auto alignment to only worry about Y and Rot #104
  src/main/java/auto/AutoAlignment.java
  src/main/java/calc/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/hardware/Swerve.java
Labels: enhancement, logic, needs testing, teleop
